[package]
name = "ismcts"
version = "0.2.4"
edition = "2021"
license = "MIT"
repository = "https://github.com/dewaeq/ismcts"
description = "Information Set Monte Carlo Tree Search"
readme = "README.md"

[dependencies]
romu = "0.6.0"
